/**
 * One-off course generator.
 *
 * Builds a brand-new course strictly from the uploaded analytic-philosophy book.
 * Each lecture is generated by feeding the model ONLY that chapter's source text
 * plus a strict "teach only from this source" instruction. Assignments are
 * generated from the produced lectures.
 *
 * Bundle with scripts/build-gen.mjs, then run the resulting .mjs with node.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";
import { openai } from "@workspace/integrations-openai-ai-server";

// Minimal concurrency limiter (avoids depending on p-limit, which is not
// resolvable from this package).
function pLimit(concurrency: number) {
  let active = 0;
  const queue: Array<() => void> = [];
  const next = () => {
    if (active >= concurrency) return;
    const run = queue.shift();
    if (run) {
      active++;
      run();
    }
  };
  return function <T>(fn: () => Promise<T>): Promise<T> {
    return new Promise<T>((resolve, reject) => {
      const run = () => {
        fn()
          .then(resolve, reject)
          .finally(() => {
            active--;
            next();
          });
      };
      queue.push(run);
      next();
    });
  };
}

const TEXT_MODEL = "gpt-5.4";

const WS = "/home/runner/workspace";
const BOOK = path.join(
  WS,
  "attached_assets/Pasted--PART-I-The-Analysis-of-Analysis-Chapter-1-Analytic-Phi_1780961071154.txt",
);
const CONTENT_DIR = path.join(WS, "artifacts/api-server/src/content");
const TOPICS_OUT = path.join(CONTENT_DIR, "topics.json");
const ASSIGN_OUT = path.join(CONTENT_DIR, "graded-assignments.json");

const LIMIT = process.env.LIMIT ? parseInt(process.env.LIMIT, 10) : 0; // 0 = all
const PHASE = process.env.PHASE ?? "all"; // "lectures" | "assignments" | "all"
const FORCE = process.env.FORCE === "1";
const CONCURRENCY = process.env.CONCURRENCY ? parseInt(process.env.CONCURRENCY, 10) : 4;

type Chapter = { n: number; unit: number; start: number; end: number };

// Chapter line ranges in the source text (1-indexed, end inclusive).
const CHAPTERS: Chapter[] = [
  // Unit 1 — Part I: The Analysis of Analysis
  { n: 1, unit: 1, start: 10, end: 860 },
  { n: 2, unit: 1, start: 861, end: 1139 },
  { n: 3, unit: 1, start: 1140, end: 1394 },
  // Unit 2 — Part II: Philosophy of Language
  { n: 4, unit: 2, start: 1400, end: 1739 },
  { n: 5, unit: 2, start: 1740, end: 1885 },
  { n: 6, unit: 2, start: 1886, end: 2170 },
  { n: 7, unit: 2, start: 2171, end: 2535 },
  { n: 8, unit: 2, start: 2536, end: 3138 },
  { n: 9, unit: 2, start: 3139, end: 3447 },
  // Unit 3 — Part III: Knowledge (Epistemology)
  { n: 10, unit: 3, start: 3453, end: 3857 },
  { n: 11, unit: 3, start: 3858, end: 4153 },
  { n: 12, unit: 3, start: 4154, end: 4326 },
  { n: 13, unit: 3, start: 4327, end: 4734 },
  // Unit 4 — Part IV: Metaphysics
  { n: 14, unit: 4, start: 4740, end: 4849 },
  { n: 15, unit: 4, start: 4850, end: 5144 },
  { n: 16, unit: 4, start: 5145, end: 5582 },
  { n: 17, unit: 4, start: 5583, end: 6225 },
  { n: 18, unit: 4, start: 6226, end: 6639 },
  // Unit 5 — Part V: Value (Ethics & Religion)
  { n: 19, unit: 5, start: 6647, end: 6864 },
  { n: 20, unit: 5, start: 6865, end: 6983 },
  { n: 21, unit: 5, start: 6984, end: 7166 },
  { n: 22, unit: 5, start: 7167, end: 7418 },
  { n: 23, unit: 5, start: 7419, end: 7574 },
  { n: 24, unit: 5, start: 7575, end: 7726 },
  { n: 25, unit: 5, start: 7727, end: 8020 },
  { n: 26, unit: 5, start: 8021, end: 8096 },
  { n: 27, unit: 5, start: 8097, end: 9168 },
];

const UNIT_TITLES: Record<number, string> = {
  1: "The Analysis of Analysis",
  2: "Philosophy of Language",
  3: "Knowledge & Epistemology",
  4: "Metaphysics, Mind & Modality",
  5: "Ethics, Value & Religion",
};

type Topic = {
  slug: string;
  title: string;
  weekNumber: number;
  blurb: string;
  lectureTitle: string;
  body: string;
  // internal
  _chapter: number;
};

type Problem = {
  topicSlug: string;
  prompt: string;
  correctAnswer: string;
  explanation: string;
  hint?: string;
};

type Assignment = {
  kind: "homework" | "test" | "midterm" | "final";
  title: string;
  weekNumber: number;
  isTimed: boolean;
  timeLimitMinutes: number | null;
  instructions: string;
  problems: Problem[];
};

const bookLines = readFileSync(BOOK, "utf8").split("\n");
function chapterText(c: Chapter): string {
  return bookLines.slice(c.start - 1, c.end).join("\n").trim();
}

function log(msg: string): void {
  const t = new Date().toISOString().slice(11, 19);
  console.log(`[${t}] ${msg}`);
}

// ---------------- Lecture generation ----------------

const LECTURE_SYS = `You are a distinguished professor writing ONE lecture for a rigorous, upper-level university course in analytic philosophy.

ABSOLUTE GROUNDING RULE: Use ONLY the ideas, distinctions, arguments, examples, terminology, and named thinkers that appear in the SOURCE TEXT provided by the user. Do NOT import outside philosophy, do NOT invent your own examples, do NOT soften or popularize away from the source. If the source argues for a controversial or non-standard position, present THAT position as the lecture's view (you are teaching this author's course, not a neutral survey). Reproduce the source's own examples verbatim in spirit (e.g. "the present King of France", "square circle", a specific named person, etc.).

DENSITY: Write a dense, substantive lecture of roughly 1900-2700 words. Walk through each argument step by step, define every technical term the source uses on first appearance, and preserve the logical structure (premises -> conclusion, objection -> reply). Prefer depth over breadth: it is better to fully develop the chapter's core arguments than to name-drop everything.

TONE: Authoritative, precise, and clear — a brilliant lecturer making hard material followable. Use concrete worked examples from the source. No filler, no "in this lecture we will", no exercises, no summary of what philosophy is in general.

OUTPUT FORMAT — respond in EXACTLY this shape and nothing else:
TITLE: <a concise 3-8 word topic title drawn from the source content>
BLURB: <one sentence, max 140 characters, catalog-style description of the lecture>
===BODY===
<GitHub-flavored Markdown. Begin with a single H1 ("# <title>"). Use ## section headers, **bold** for key technical terms on first use, and numbered/bulleted lists for argument steps. Do not include any exercises or questions.>`;

async function generateLecture(c: Chapter): Promise<{ title: string; blurb: string; body: string }> {
  const src = chapterText(c);
  const user = `SOURCE TEXT — Chapter ${c.n} (this is the ONLY material you may teach from):\n\n${src}`;
  const resp = await openai.chat.completions.create({
    model: TEXT_MODEL,
    max_completion_tokens: 8000,
    messages: [
      { role: "system", content: LECTURE_SYS },
      { role: "user", content: user },
    ],
  });
  const out = resp.choices[0]?.message?.content?.trim() ?? "";
  const titleM = out.match(/^TITLE:\s*(.+)$/m);
  const blurbM = out.match(/^BLURB:\s*(.+)$/m);
  const bodyIdx = out.indexOf("===BODY===");
  const body = (bodyIdx >= 0 ? out.slice(bodyIdx + "===BODY===".length) : out).trim();
  const title = titleM?.[1]?.trim().replace(/[*#]/g, "") || `Chapter ${c.n}`;
  const blurb = blurbM?.[1]?.trim().replace(/[*#]/g, "") || "";
  if (body.length < 600) {
    throw new Error(`Chapter ${c.n}: body too short (${body.length} chars) — likely a bad generation`);
  }
  return { title, blurb, body };
}

function loadTopics(): Topic[] {
  if (existsSync(TOPICS_OUT)) {
    try {
      return JSON.parse(readFileSync(TOPICS_OUT, "utf8")) as Topic[];
    } catch {
      return [];
    }
  }
  return [];
}

function writeTopics(topics: Topic[]): void {
  const ordered = [...topics].sort((a, b) => a._chapter - b._chapter);
  // recompute lectureTitle as <unit>.<position-in-unit>
  const perUnit: Record<number, number> = {};
  for (const t of ordered) {
    perUnit[t.weekNumber] = (perUnit[t.weekNumber] ?? 0) + 1;
    t.lectureTitle = `${t.weekNumber}.${perUnit[t.weekNumber]} ${t.title}`;
  }
  writeFileSync(TOPICS_OUT, JSON.stringify(ordered, null, 2) + "\n");
}

async function runLectures(): Promise<Topic[]> {
  let chapters = CHAPTERS;
  if (LIMIT > 0) chapters = chapters.slice(0, LIMIT);

  const existing = loadTopics();
  const bySlug = new Map<string, Topic>(existing.map((t) => [t.slug, t]));

  const limit = pLimit(CONCURRENCY);
  let done = 0;
  await Promise.all(
    chapters.map((c) =>
      limit(async () => {
        const slug = `ch${c.n}`;
        if (!FORCE && bySlug.get(slug)?.body) {
          log(`skip ch${c.n} (already generated)`);
          done++;
          return;
        }
        log(`generating ch${c.n} (unit ${c.unit})...`);
        const { title, blurb, body } = await generateLecture(c);
        const topic: Topic = {
          slug,
          title,
          weekNumber: c.unit,
          blurb,
          lectureTitle: `${c.unit}.0 ${title}`,
          body,
          _chapter: c.n,
        };
        bySlug.set(slug, topic);
        writeTopics([...bySlug.values()]); // incremental save
        done++;
        log(`  done ch${c.n}: "${title}" (${body.length} chars) [${done}/${chapters.length}]`);
      }),
    ),
  );
  const all = [...bySlug.values()].sort((a, b) => a._chapter - b._chapter);
  writeTopics(all);
  log(`lectures complete: ${all.length} topics`);
  return all;
}

// ---------------- Assignment generation ----------------

function unitContext(topics: Topic[], units: number[], perTopicChars: number): { text: string; slugs: string[] } {
  const subset = topics.filter((t) => units.includes(t.weekNumber));
  const slugs = subset.map((t) => t.slug);
  const text = subset
    .map((t) => `### topicSlug: ${t.slug} — ${t.title}\n${t.body.slice(0, perTopicChars)}`)
    .join("\n\n");
  return { text, slugs };
}

function probSys(n: number, slugs: string[]): string {
  return `You are writing exam problems for a rigorous analytic-philosophy course, based ONLY on the lecture material the user provides.

Output STRICT JSON of the form:
{"problems":[{"topicSlug":"...","prompt":"...","correctAnswer":"...","explanation":"...","hint":"..."}]}

RULES:
- Produce EXACTLY ${n} problems.
- "topicSlug" MUST be one of: ${slugs.join(", ")}. Distribute problems across several of these topics.
- Each "prompt" must present a CONCRETE scenario, dialogue, argument, or worked case and ask the student to APPLY the course's concepts — analyze, reconstruct, evaluate, find a counterexample, or apply a distinction. NEVER ask "define X" or "what is Y".
- Ground every problem STRICTLY in the supplied lecture material — use that material's own arguments, distinctions, and examples. Do not introduce outside philosophy.
- "correctAnswer": a model answer of 150-300 words that a strong student would write, in prose.
- "explanation": 1-2 sentences naming the principle being tested and what a strong answer must show.
- "hint" is optional; include it only when genuinely useful.
Return ONLY the JSON object.`;
}

async function generateProblems(n: number, units: number[], topics: Topic[], perTopicChars: number): Promise<Problem[]> {
  const { text, slugs } = unitContext(topics, units, perTopicChars);
  const resp = await openai.chat.completions.create({
    model: TEXT_MODEL,
    max_completion_tokens: 8000,
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: probSys(n, slugs) },
      { role: "user", content: `LECTURE MATERIAL (the only source you may use):\n\n${text}` },
    ],
  });
  const raw = resp.choices[0]?.message?.content?.trim() ?? "{}";
  let parsed: { problems?: Problem[] };
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error(`Problem JSON parse failed for units ${units.join(",")}`);
  }
  const allowed = new Set(slugs);
  const problems = (parsed.problems ?? []).filter((p) => p && allowed.has(p.topicSlug) && p.prompt && p.correctAnswer);
  if (problems.length === 0) throw new Error(`No valid problems for units ${units.join(",")}`);
  return problems.map((p) => ({
    topicSlug: p.topicSlug,
    prompt: p.prompt,
    correctAnswer: p.correctAnswer,
    explanation: p.explanation ?? "",
    ...(p.hint ? { hint: p.hint } : {}),
  }));
}

type AssignSpec = {
  kind: Assignment["kind"];
  title: string;
  weekNumber: number;
  isTimed: boolean;
  timeLimitMinutes: number | null;
  instructions: string;
  count: number;
  units: number[];
  perTopicChars: number;
};

function assignmentSpecs(): AssignSpec[] {
  const specs: AssignSpec[] = [];
  for (const u of [1, 2, 3, 4, 5]) {
    specs.push({
      kind: "homework",
      title: `Homework ${u} — ${UNIT_TITLES[u]}`,
      weekNumber: u,
      isTimed: false,
      timeLimitMinutes: null,
      instructions: "Untimed practice. Answer each question in a few complete sentences, in your own words.",
      count: 5,
      units: [u],
      perTopicChars: 4500,
    });
    specs.push({
      kind: "test",
      title: `Unit ${u} Test — ${UNIT_TITLES[u]}`,
      weekNumber: u,
      isTimed: true,
      timeLimitMinutes: 45,
      instructions: "Timed test. Answer each question thoroughly and in your own words.",
      count: 5,
      units: [u],
      perTopicChars: 4500,
    });
    if (u === 3) {
      specs.push({
        kind: "midterm",
        title: "Midterm Examination — Units 1–3",
        weekNumber: 3,
        isTimed: true,
        timeLimitMinutes: 90,
        instructions: "Timed midterm covering Units 1–3. Answer each question thoroughly in your own words.",
        count: 6,
        units: [1, 2, 3],
        perTopicChars: 1800,
      });
    }
  }
  specs.push({
    kind: "final",
    title: "Final Examination — Comprehensive",
    weekNumber: 5,
    isTimed: true,
    timeLimitMinutes: 120,
    instructions: "Timed comprehensive final covering all five units. Answer each question thoroughly in your own words.",
    count: 8,
    units: [1, 2, 3, 4, 5],
    perTopicChars: 1400,
  });
  return specs;
}

function loadAssignments(): Assignment[] {
  if (existsSync(ASSIGN_OUT)) {
    try {
      const data = JSON.parse(readFileSync(ASSIGN_OUT, "utf8")) as Assignment[];
      if (Array.isArray(data)) return data;
    } catch {
      // ignore — will regenerate
    }
  }
  return [];
}

function writeAssignments(byTitle: Map<string, Assignment>): void {
  const order: Record<string, number> = { homework: 0, test: 1, midterm: 2, final: 3 };
  const sorted = [...byTitle.values()].sort(
    (a, b) => a.weekNumber - b.weekNumber || order[a.kind]! - order[b.kind]!,
  );
  writeFileSync(ASSIGN_OUT, JSON.stringify(sorted, null, 2) + "\n");
}

async function runAssignments(topics: Topic[]): Promise<Assignment[]> {
  const specs = assignmentSpecs();
  const existing = loadAssignments();
  // Only treat prior assignments as resumable if they already match the new schema
  // (i.e. one of our generated titles). Legacy content is dropped.
  const validTitles = new Set(specs.map((s) => s.title));
  const byTitle = new Map<string, Assignment>(
    existing.filter((a) => validTitles.has(a.title) && a.problems?.length).map((a) => [a.title, a]),
  );

  const limit = pLimit(CONCURRENCY);
  let done = byTitle.size;
  await Promise.all(
    specs.map((spec) =>
      limit(async () => {
        if (byTitle.has(spec.title)) {
          log(`skip assignment "${spec.title}" (already generated)`);
          return;
        }
        log(`generating assignment "${spec.title}"...`);
        const problems = await generateProblems(spec.count, spec.units, topics, spec.perTopicChars);
        byTitle.set(spec.title, {
          kind: spec.kind,
          title: spec.title,
          weekNumber: spec.weekNumber,
          isTimed: spec.isTimed,
          timeLimitMinutes: spec.timeLimitMinutes,
          instructions: spec.instructions,
          problems,
        });
        writeAssignments(byTitle); // incremental save
        done++;
        log(`  done "${spec.title}" (${problems.length} problems) [${done}/${specs.length}]`);
      }),
    ),
  );

  writeAssignments(byTitle);
  const all = [...byTitle.values()];
  log(`assignments complete: ${all.length} assignments, ${all.reduce((n, a) => n + a.problems.length, 0)} problems`);
  return all;
}

// ---------------- Main ----------------

async function main(): Promise<void> {
  if (!existsSync(CONTENT_DIR)) mkdirSync(CONTENT_DIR, { recursive: true });
  log(`PHASE=${PHASE} LIMIT=${LIMIT} FORCE=${FORCE} CONCURRENCY=${CONCURRENCY}`);

  let topics: Topic[] = [];
  if (PHASE === "lectures" || PHASE === "all") {
    topics = await runLectures();
  } else {
    topics = loadTopics();
  }

  if (PHASE === "assignments" || PHASE === "all") {
    if (topics.length === 0) topics = loadTopics();
    await runAssignments(topics);
  }

  log("ALL DONE");
}

main().catch((err) => {
  console.error("GENERATION FAILED:", err);
  process.exit(1);
});
